### PR TITLE
lrem() function - parameters order fixed

### PR DESCRIPTION
**Pull request by alex-scott**
Seems predis has different parameters order than REDIS server. Just fixed function to match PHP extension

### CODE REVIEW

**Comment by Oliboy50** [comment]
thanks @alex-scott :wave: 

could you link some documentation about this, please?

**Comment by alex-scott** [comment]
> thanks @alex-scott 
> 
> could you link some documentation about this, please?

Sure https://github.com/phpredis/phpredis#lrem-lremove

**Comment by Oliboy50** [comment]
thanks 👌 

indeed, it seems to be a "predis only" stuff:

> Note: The argument order is not the same as in the Redis documentation. This difference is kept for compatibility reasons

but since we've put the following statement [in our documentation](https://github.com/M6Web/RedisMock#redis-php-mock--):

> Work for now only with predis

maybe we should follow up with the predis parameters order too

**Comment by Oliboy50** [comment]
@alex-scott => https://github.com/M6Web/RedisMock/releases/tag/v5.0.0

**Pull request merged**
