### PR TITLE
Test SINTER and refactor

### PR DESCRIPTION
**Pull request by tomlankhorst**
Refactors [`SINTER`](https://redis.io/commands/sinter) like `SDIFF` #78 and add test.

> ```
> key1 = {a,b,c,d}
> key2 = {c}
> key3 = {a,c,e}
> SINTER key1 key2 key3 = {c}
> ```

Test

```php
$redisMock = new Redis();
$redisMock->sadd('key1', 'a', 'b', 'c', 'd');
$redisMock->sadd('key2', 'c');
$redisMock->sadd('key3', 'a', 'c', 'e');
$this->assert
    ->array($redisMock->sinter('key1', 'key2', 'key3'))
    ->isEqualTo(['c']);
```

### CODE REVIEW

**Comment by omansour** [comment]
hey @tomlankhorst - can you please make the PR mergeable ? Many thanks

**Comment by tomlankhorst** [comment]
Rebased... 👌

**Comment by tomlankhorst** [comment]
By the way, have you got your Packagist Github callbacks in place? :)

**Comment by omansour** [comment]
v4.5.0

**Pull request merged**
