### PR TITLE
Add hincrby command

### PR DESCRIPTION
**Pull request by sforsberg**
## What? Why? 
Adds support for `hincrby` command.

Includes some tests and updates the README.

### CODE REVIEW

**Comment by josiasmontag** [comment]
Can we get this merged? Thanks!

**Comment by omansour** [comment]
test arent passing. Can you rebase your branch on master @sforsberg ?

**Comment by sforsberg** [comment]
@omansour Rebased with master and tests now look good! @josiasmontag

**Comment by omansour** [comment]
v3.2.0

**Pull request merged**
