### PR TITLE
Added scripting commands (#eval, #evalsha)

### PR DESCRIPTION
**Pull request by sevrugin**
… which are just stubs—they won't execute anything

### CODE REVIEW

**Comment by omansour** [comment]
okay for me - in order to let the tests pass

**Comment by omansour** [comment]
v4.2.0

**Comment by josiasmontag** [comment]
Could you please publish 4.2 on Packagist also?

**Comment by mikaelrandy** [comment]
@josiasmontag It's done !
Thanks.

**Pull request merged**
